version: 2

jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: clientcomm
          RAILS_ENV: test
          TWILIO_PHONE_NUMBER: +12435551212
          TWILIO_AUTH_TOKEN: TWILIOAUTHTOKENTWILIOAUTHTOKENTWIL
          MIXPANEL_TOKEN: MIXPANELTOKENMIXPANELTOKENMIXPANEL
          UNCLAIMED_EMAIL: unclaimed@example.com
          TYPEFORM_LINK: example.com
          MASS_MESSAGES: 'true'
          DEPLOY_BASE_URL: 'https://test.example.org'
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: clientcomm
          POSTGRES_GB: clientcomm-test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore bundler cache
      - type: cache-restore
        key: clientcomm-bundle-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      # Save bundler cache
      - type: cache-save
        key: clientcomm-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      #Run rubocop
      - run:
          name: rubocop
          command: 'bundle exec rubocop -R'

      # Prepare db
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate

      #Run tests
      - run:
          name: rspec
          command: 'bin/test'

      #Save test results
      - store_test_results:
          path: results/rspec

      #Save artifacts
      - store_artifacts:
          path: tmp/capybara/artifacts

      - store_artifacts:
          path: coverage
          prefix: coverage

      - run:
          name: codeclimate
          command: 'bin/codeclimate'

  brakeman:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: brakeman
          command: 'bin/brakeman'

  bundler-audit:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: bundler-audit
          command: 'bin/bundler-audit'

  merge_master:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "7a:a4:eb:b7:19:13:6a:63:8a:32:ac:a7:8a:d2:b2:21"
      - run:
          command: |
            git checkout master
            git merge --ff-only develop
            git push

workflows:
  version: 2
  test:
    jobs:
      - rspec:
          filters:
            branches:
              ignore: master
      - brakeman:
          filters:
            branches:
              ignore: master
      - bundler-audit:
          filters:
            branches:
              ignore: master
      - merge_master:
          filters:
            branches:
              only: develop
          requires:
            - rspec
            - brakeman
            - bundler-audit
